[package]
name = "assetmanager"
version = "0.1.0"
edition = "2018"

[dependencies]
ink_primitives = { version = "3.0.0-rc2", default-features = false }
ink_metadata = { version = "3.0.0-rc2", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc2", default-features = false }
ink_storage = { version = "3.0.0-rc2", default-features = false }
ink_lang = { version = "3.0.0-rc2", default-features = false }
ink_prelude = { version = "3.0.0-rc2", default-features = false }

scale = { package = "parity-scale-codec", version = "1.3", default-features = false, features = ["derive"] }
<<<<<<< HEAD
erc20 = { version = "0.1.0", path = "erc20", default-features = false, features = ["ink-as-dependency"] }
erc721 = { version = "0.1.0", path = "erc721", default-features = false, features = ["ink-as-dependency"] }
scale-info = { version = "0.4.1", default-features = false, features = ["derive"], optional = true }

=======
administration = { version = "0.1.0", path = "administration", default-features = false, features = ["ink-as-dependency"] }
lendingmanager = { version = "0.1.0", path = "lendingmanager", default-features = false, features = ["ink-as-dependency"] }
erc20 = { version = "0.1.0", path = "erc20", default-features = false, features = ["ink-as-dependency"] }
scale-info = { version = "0.4.1", default-features = false, features = ["derive"], optional = true }


>>>>>>> 66390869c7dc304838272d1ef6afbe20d485a418
[lib]
name = "assetmanager"
path = "lib.rs"
crate-type = [
	# Used for normal contract Wasm blobs.
	"cdylib",
]

[features]
default = ["std"]
std = [
<<<<<<< HEAD
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_primitives/std",
    "scale/std",
    "scale-info/std",

    "erc20/std",
    "erc721/std",
]
ink-as-dependency = []

[profile.release] 
overflow-checks = false
=======
    "ink_primitives/std",
    "ink_metadata",
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_lang/std",
    "scale/std",
    "scale-info",
    "scale-info/std",

    "administration/std",
    "lendingmanager/std",
    "erc20/std",
]
ink-as-dependency = []
>>>>>>> 66390869c7dc304838272d1ef6afbe20d485a418
